name = "greenback"
main = "build/worker/shim.mjs"
compatibility_date = "2023-04-19"

[vars]
WORKERS_RS_VERSION = "0.0.11"

[build]
command = "cargo install -q worker-build --version 0.0.9 && worker-build --release"

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "greenback-db"
database_id = "364c7459-b5e9-4f8a-bad1-972f0b2fcf55"
